server:
  port: 8080
  servlet:
    context-path: /bootcamp2

spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: postgres://obgumnaxrgbaar:3ef6decf5543f0c9b432e238793b6a2f7038fe59adc716fb23723e4ced128d87@ec2-34-193-112-164.compute-1.amazonaws.com:5432/d4gup80d93atbg
      username: obgumnaxrgbaar
      password: 3ef6decf5543f0c9b432e238793b6a2f7038fe59adc716fb23723e4ced128d87
    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-dll: true
      hibernate:
        ddl-auto: true

application:
    description: Projeto bootcamp DIO - Santander
